'use client';

import { useEffect, useMemo, useState } from 'react';
import Image from 'next/image';
import Link from 'next/link';
import { ArrowRight, BookOpenText, Package, Sparkles } from 'lucide-react';
import { useLangContext } from '@/components/layout/LangContext';

type PublicIp = { id: string; name_ko: string; name_zh: string; slug: string; description_ko: string; description_zh: string; profile_image_url: string; banner_url: string; world_name_ko: string; world_name_zh: string; world_summary_ko: string; world_summary_zh: string; color_primary: string; color_secondary: string; };
type PublicCast = { id: string; ip_character_id: string; name_ko: string; name_zh: string; role_ko: string; role_zh: string; profile_ko: string; profile_zh: string; profile_image_url: string; };
type PublicContent = { id: string; ip_character_id: string; content_type: string; episode_no: number | null; slug: string; title_ko: string; title_zh: string; excerpt_ko: string; excerpt_zh: string; };
type PublicData = { ips: PublicIp[]; cast: PublicCast[]; content: PublicContent[] };

const fallback = [
  { id: 'fallback-duckle', name_ko: '길덕이', name_zh: '吉鸭', slug: 'duckle', description_ko: '변신천재 유연한 오리', description_zh: '灵活百变的小鸭', profile_image_url: '/images/hero-characters/gilduck.webp', world_name_ko: '길덕이의 유쾌한 일상', world_name_zh: '吉鸭的趣味日常', world_summary_ko: '일상의 작은 순간을 유연하고 유쾌하게 풀어내는 캐릭터입니다.', world_summary_zh: '用灵活又愉快的方式描绘日常小瞬间的角色。', color_primary: '#B45309', color_secondary: '#FEF3C7' },
  { id: 'fallback-inyeoseok', name_ko: '이녀석', name_zh: '这家伙', slug: 'inyeoseok', description_ko: '재미있는 낙서 캐릭터', description_zh: '有趣的涂鸦角色', profile_image_url: '/images/hero-characters/inyeoseok.webp', world_name_ko: '자유로운 낙서의 표정', world_name_zh: '自由涂鸦的表情', world_summary_ko: '자유로운 낙서의 선과 표정을 바탕으로 다양한 굿즈로 확장하는 캐릭터 브랜드입니다.', world_summary_zh: '以自由涂鸦的线条和表情为基础，延展为多样周边的角色品牌。', color_primary: '#334155', color_secondary: '#E2E8F0' },
  { id: 'fallback-kkomul', name_ko: '꼬물이들', name_zh: '小怪物们', slug: 'kkomul', description_ko: '우주에서 온 몬스터', description_zh: '来自宇宙的小怪物', profile_image_url: '/images/hero-characters/kkomul.webp', world_name_ko: '낯선 우주의 친구들', world_name_zh: '陌生宇宙的朋友们', world_summary_ko: '낯선 우주에서 찾아온 개성 있는 친구들의 모험을 담은 캐릭터입니다.', world_summary_zh: '记录来自陌生宇宙的个性伙伴们冒险的角色。', color_primary: '#6D28D9', color_secondary: '#EDE9FE' },
  { id: 'fallback-heartbbung', name_ko: '하트뿅 햄스터', name_zh: '爱心仓鼠', slug: 'heartbbung', description_ko: '마음을 전하는 햄스터', description_zh: '传递心意的仓鼠', profile_image_url: '/images/hero-characters/heartbbung.webp', world_name_ko: '마음을 전하는 손짓', world_name_zh: '传递心意的小手势', world_summary_ko: '작은 손짓과 표정으로 다정한 마음을 전하는 캐릭터입니다.', world_summary_zh: '用小小手势和表情传递温暖心意的角色。', color_primary: '#DB2777', color_secondary: '#FCE7F3' },
  { id: 'fallback-piggly', name_ko: '피글리', name_zh: '皮格利', slug: 'piggly', description_ko: '동글동글 귀여운 돼지', description_zh: '圆滚滚的可爱小猪', profile_image_url: '/images/hero-characters/piggly.webp', world_name_ko: '편안한 하루의 친구', world_name_zh: '轻松一天的朋友', world_summary_ko: '부드러운 실루엣과 편안한 표정이 매력인 일상형 캐릭터입니다.', world_summary_zh: '以柔和轮廓和轻松表情见长的日常角色。', color_primary: '#E11D48', color_secondary: '#FFE4E6' },
] as PublicIp[];

const copy = {
  ko: { eyebrow: 'ORIGINAL IP', title: '이야기에서 시작해 상품으로 이어지는 KERYX의 자체 디자인 IP', description: '운영자가 공개한 IP, 캐릭터, 세계관과 연재 콘텐츠를 한 흐름으로 소개합니다.', characterCta: 'IP 보기', storeCta: '상품 스토어', sectionEyebrow: 'IP ARCHIVE', sectionTitle: '공개된 IP와 세계관', sectionDescription: '각 IP의 이야기와 디자인 언어를 확인하고, 관련 상품을 함께 살펴보세요.', productLink: '관련 상품 보기', cast: '캐릭터', series: '연재', storyEyebrow: 'STORY ARCHIVE', storyTitle: '세계관 아카이브', storyDescription: '캐릭터가 태어난 배경과 관계, 디자인 모티프를 콘텐츠 중심으로 살펴봅니다.', storyLink: '스토리 보기', serialEyebrow: 'SERIAL CONTENT', serialTitle: '동화·웹툰·소설 연재', serialDescription: '캐릭터의 이야기를 지속적으로 쌓아가며, 다음 콘텐츠와 상품 아이디어로 연결합니다.', serialLink: '연재 보기', connectionEyebrow: 'PRODUCT CONNECTION', connectionTitle: 'IP가 적용된 상품을 직접 확인해 보세요.', connectionDescription: '판매 준비가 완료된 상품만 스토어에 공개합니다.', connectionCta: 'KERYX 스토어', loading: '공개 IP를 불러오는 중입니다.', fallback: '운영자 등록 데이터가 공개되면 이 영역에 즉시 반영됩니다.' },
  zh: { eyebrow: 'ORIGINAL IP', title: '从故事出发，延展为商品的 KERYX 原创设计 IP', description: '以一个完整的流程介绍运营者公开的IP、角色、世界观和连载内容。', characterCta: '查看IP', storeCta: '商品商店', sectionEyebrow: 'IP ARCHIVE', sectionTitle: '已公开的IP与世界观', sectionDescription: '了解每个IP的故事与设计语言，并查看相关商品。', productLink: '查看相关商品', cast: '角色', series: '连载', storyEyebrow: 'STORY ARCHIVE', storyTitle: '世界观档案', storyDescription: '以内容为中心了解角色诞生的背景、关系和设计灵感。', storyLink: '查看故事', serialEyebrow: 'SERIAL CONTENT', serialTitle: '童话·漫画·小说连载', serialDescription: '持续积累角色故事，并连接下一阶段的内容和商品创意。', serialLink: '查看连载', connectionEyebrow: 'PRODUCT CONNECTION', connectionTitle: '直接了解应用 IP 的商品。', connectionDescription: '仅在商店公开已完成销售准备的商品。', connectionCta: 'KERYX 商店', loading: '正在加载公开IP。', fallback: '运营者公开登记的数据将立即显示在这里。' },
};

export function IpHubContent() {
  const { lang } = useLangContext();
  const t = copy[lang];
  const [data, setData] = useState<PublicData>({ ips: [], cast: [], content: [] });
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    fetch('/api/public/ip', { cache: 'no-store' })
      .then((response) => response.ok ? response.json() : Promise.reject(new Error('failed')))
      .then((value) => setData(value))
      .catch(() => setData({ ips: [], cast: [], content: [] }))
      .finally(() => setLoading(false));
  }, []);

  const ips = data.ips.length > 0 ? data.ips : fallback;
  const castByIp = useMemo(() => new Map(data.cast.map((item) => [item.ip_character_id, item])), [data.cast]);
  const contentCountByIp = useMemo(() => data.content.reduce((map, item) => map.set(item.ip_character_id, (map.get(item.ip_character_id) ?? 0) + 1), new Map<string, number>()), [data.content]);

  return <main>
    <section className="border-b border-stone-200 bg-white"><div className="mx-auto max-w-screen-xl px-4 py-12 sm:px-6 sm:py-20 lg:px-8"><p className="text-xs font-black tracking-[0.18em] text-orange-700">{t.eyebrow}</p><h1 className="mt-3 max-w-3xl text-4xl font-black leading-tight tracking-tight sm:text-5xl">{t.title}</h1><p className="mt-6 max-w-2xl text-base leading-7 text-stone-600">{t.description}</p><div className="mt-8 flex flex-col gap-3 sm:flex-row"><Link href="#characters" className="inline-flex min-h-12 items-center justify-center gap-2 rounded-xl bg-stone-950 px-5 text-sm font-bold text-white no-underline transition hover:bg-stone-800 active:scale-95"><Sparkles className="h-4 w-4" />{t.characterCta}</Link><Link href="/shop" className="inline-flex min-h-12 items-center justify-center gap-2 rounded-xl border border-stone-300 bg-white px-5 text-sm font-bold text-stone-800 no-underline transition hover:bg-stone-100 active:scale-95"><Package className="h-4 w-4" />{t.storeCta}</Link></div></div></section>
    <section id="characters" className="mx-auto max-w-screen-xl px-4 py-12 sm:px-6 lg:px-8 lg:py-16"><div className="flex flex-col gap-3 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-xs font-black tracking-[0.16em] text-orange-700">{t.sectionEyebrow}</p><h2 className="mt-2 text-3xl font-black tracking-tight">{t.sectionTitle}</h2></div><p className="max-w-md text-base leading-7 text-stone-600">{t.sectionDescription}</p></div>{loading ? <p className="mt-8 text-sm text-stone-500">{t.loading}</p> : null}{!loading && data.ips.length === 0 ? <p className="mt-4 text-sm text-stone-500">{t.fallback}</p> : null}<div className="mt-8 grid grid-cols-1 gap-4 sm:grid-cols-2 lg:grid-cols-3">{ips.map((ip) => { const cast = castByIp.get(ip.id); const count = contentCountByIp.get(ip.id) ?? 0; const name = lang === 'zh' && ip.name_zh ? ip.name_zh : ip.name_ko; const intro = lang === 'zh' && ip.description_zh ? ip.description_zh : ip.description_ko; const world = lang === 'zh' && ip.world_name_zh ? ip.world_name_zh : ip.world_name_ko; const summary = lang === 'zh' && ip.world_summary_zh ? ip.world_summary_zh : ip.world_summary_ko; const image = ip.profile_image_url || ip.banner_url; return <article key={ip.id} className="group overflow-hidden rounded-3xl border border-stone-200 bg-white shadow-sm transition hover:-translate-y-1 hover:shadow-lg"><div className="relative aspect-square overflow-hidden bg-stone-100">{image ? <Image src={image} alt={`${name} ${lang === 'ko' ? '캐릭터' : '角色'}`} fill sizes="(max-width: 640px) 100vw, (max-width: 1024px) 50vw, 33vw" className="object-cover transition duration-500 group-hover:scale-105" /> : <div className="flex h-full items-center justify-center text-sm text-stone-400">KERYX IP</div>}</div><div className="p-5"><p className="text-sm font-bold text-orange-700">{intro}</p><h3 className="mt-1 text-xl font-black">{name}</h3>{world && <p className="mt-3 text-sm font-bold text-stone-800">{world}</p>}{summary && <p className="mt-1 text-sm leading-6 text-stone-600">{summary}</p>}{cast && <p className="mt-3 text-xs font-semibold text-stone-500">{t.cast}: {lang === 'zh' && cast.name_zh ? cast.name_zh : cast.name_ko}</p>}{count > 0 && <p className="mt-1 text-xs font-semibold text-stone-500">{t.series}: {count}</p>}<Link href="/shop" className="mt-5 inline-flex min-h-11 items-center gap-2 text-sm font-black text-stone-950 no-underline transition hover:text-orange-700 active:scale-95">{t.productLink}<ArrowRight className="h-4 w-4" /></Link></div></article>; })}</div></section>
    <section className="mx-auto grid max-w-screen-xl gap-4 px-4 pb-4 sm:px-6 lg:grid-cols-2 lg:px-8"><Link href="/ip-story" className="rounded-3xl bg-stone-950 p-6 text-white no-underline transition hover:bg-stone-800 active:scale-[0.99] sm:p-8"><BookOpenText className="h-6 w-6 text-orange-300" /><p className="mt-7 text-xs font-black tracking-[0.16em] text-orange-200">{t.storyEyebrow}</p><h2 className="mt-2 text-2xl font-black">{t.storyTitle}</h2><p className="mt-3 max-w-lg text-sm leading-6 text-stone-300">{t.storyDescription}</p><span className="mt-6 inline-flex min-h-11 items-center gap-2 text-sm font-bold">{t.storyLink}<ArrowRight className="h-4 w-4" /></span></Link><Link href="/ip-serial" className="rounded-3xl border border-stone-200 bg-white p-6 text-stone-950 no-underline transition hover:border-stone-400 active:scale-[0.99] sm:p-8"><BookOpenText className="h-6 w-6 text-orange-700" /><p className="mt-7 text-xs font-black tracking-[0.16em] text-orange-700">{t.serialEyebrow}</p><h2 className="mt-2 text-2xl font-black">{t.serialTitle}</h2><p className="mt-3 max-w-lg text-sm leading-6 text-stone-600">{t.serialDescription}</p><span className="mt-6 inline-flex min-h-11 items-center gap-2 text-sm font-bold">{t.serialLink}<ArrowRight className="h-4 w-4" /></span></Link></section>
    <section className="mx-auto max-w-screen-xl px-4 py-12 sm:px-6 lg:px-8 lg:py-16"><div className="rounded-3xl border border-orange-200 bg-orange-50 p-6 sm:flex sm:items-center sm:justify-between sm:p-8"><div><p className="text-xs font-black tracking-[0.16em] text-orange-700">{t.connectionEyebrow}</p><h2 className="mt-2 text-2xl font-black">{t.connectionTitle}</h2><p className="mt-3 text-base leading-7 text-stone-600">{t.connectionDescription}</p></div><Link href="/shop" className="mt-5 inline-flex min-h-12 items-center justify-center gap-2 rounded-xl bg-stone-950 px-5 text-sm font-bold text-white no-underline transition hover:bg-stone-800 active:scale-95 sm:mt-0">{t.connectionCta}<ArrowRight className="h-4 w-4" /></Link></div></section>
  </main>;
}
