'use client';

import Link from 'next/link';
import { ArrowRight, BookOpenText, Boxes, Compass, Package, Send, Sparkles } from 'lucide-react';
import { PublicFooter } from '@/components/layout/PublicFooter';
import { RetailStoreHeader } from '@/components/retail/RetailStoreHeader';
import { BRAND } from '@/lib/brand';
import { useLangContext } from '@/components/layout/LangContext';

const copy = {
  ko: {
    eyebrow: 'ABOUT KERYX', title: '스토리가 있는 제품을 기획하여 공급합니다.', lead: '케릭스는 자체 디자인 IP의 캐릭터와 이야기를 만들고, 상품 기획·제작·판매를 하나의 흐름으로 연결합니다.',
    introTitle: '세 가지 흐름으로 운영합니다.', intro: '소개를 위한 소개가 아니라, 콘텐츠를 보고 상품을 확인하고 필요한 샘플을 신청할 수 있는 구조를 만듭니다. 모든 공개 상품과 콘텐츠는 운영자가 검토한 뒤 게시합니다.',
    pillars: [{ title: '자체 디자인 IP', description: '캐릭터의 성격, 세계관, 연재 콘텐츠를 먼저 설계하고 관리합니다.', href: '/ip', cta: 'IP 소개 보기', icon: Sparkles }, { title: '상품 스토어', description: 'IP가 적용된 상품과 판매 조건이 준비된 제품을 스토어에서 보여줍니다.', href: '/shop', cta: '상품 보기', icon: Package }, { title: '샘플 구독', description: '관심 있는 IP와 상품군을 남기면, 운영 검토 후 신상품·샘플 정보를 안내합니다.', href: '/sample-subscription', cta: '샘플 구독', icon: Send }],
    flowEyebrow: 'HOW WE WORK', flowTitle: '콘텐츠에서 상품까지 이어지는 운영 방식', flow: [{ title: 'IP와 이야기 설계', description: '캐릭터·세계관·콘텐츠의 기준을 먼저 정리합니다.' }, { title: '상품 기획과 제작', description: '캐릭터의 디자인 언어를 인형·키링·피규어 등 상품으로 확장합니다.' }, { title: '판매 조건 관리', description: '판매가, 재고, 배송 조건이 준비된 상품만 스토어에 공개합니다.' }, { title: '샘플과 신상품 안내', description: '관심 정보를 기준으로 필요한 상품과 샘플 소식을 전달합니다.' }],
    trustTitle: '운영 기준', trust: ['IP·캐릭터·연재 콘텐츠는 초안과 공개 상태를 구분해 관리합니다.', '상품 등록, 판매가 변경, 공개 전환은 운영 이력으로 남깁니다.', '공개 화면에는 원가와 공장 연락처 등 내부 운영 정보를 표시하지 않습니다.'],
    originEyebrow: 'BRAND ORIGIN', originTitle: '무역의 메신저, KERYX', origin: BRAND.etymologyKo, finalTitle: 'KERYX의 콘텐츠와 상품을 확인해 보세요.', finalDescription: 'IP 소개, 판매 상품, 샘플 구독은 서로 연결되어 있으며 각 화면에서 바로 이동할 수 있습니다.', ip: '자체 디자인 IP', shop: '상품 스토어', sample: '샘플 구독',
  },
  zh: {
    eyebrow: 'ABOUT KERYX', title: '策划并供应有故事的产品。', lead: '凯瑞打造原创设计IP的角色与故事，并将商品策划、制作与销售连接为完整流程。',
    introTitle: '以三个核心流程运营。', intro: '我们不做只用于介绍的页面，而是建立可以查看内容、确认商品、申请所需样品的结构。所有公开商品和内容都由运营人员审核后发布。',
    pillars: [{ title: '原创设计IP', description: '先设计并管理角色个性、世界观与连载内容。', href: '/ip', cta: '查看IP介绍', icon: Sparkles }, { title: '商品商店', description: '在商店展示已应用IP且具备销售条件的商品。', href: '/shop', cta: '查看商品', icon: Package }, { title: '样品订阅', description: '留下感兴趣的IP和商品类型后，经运营审核提供新品与样品资讯。', href: '/sample-subscription', cta: '订阅样品', icon: Send }],
    flowEyebrow: 'HOW WE WORK', flowTitle: '从内容到商品的运营方式', flow: [{ title: 'IP与故事设计', description: '先整理角色、世界观与内容的统一标准。' }, { title: '商品策划与制作', description: '将角色的设计语言延展为毛绒、钥匙扣、手办等商品。' }, { title: '销售条件管理', description: '仅将已准备好售价、库存与配送条件的商品公开到商店。' }, { title: '样品与新品资讯', description: '根据留下的兴趣信息传达所需商品和样品资讯。' }],
    trustTitle: '运营原则', trust: ['IP、角色与连载内容以草稿和公开状态分开管理。', '商品登记、售价变更和公开状态转换均保留运营记录。', '公开页面不显示成本、工厂联系方式等内部运营信息。'],
    originEyebrow: 'BRAND ORIGIN', originTitle: '贸易的信使，KERYX', origin: 'KERYX（凯瑞）源自希腊语 kḗrux（κῆρυξ），意为在古希腊传递神之讯息的使者。作为商业与沟通守护者赫尔墨斯的使者，KERYX表达了连接韩国、中国与世界的贸易信使这一品牌身份。', finalTitle: '了解 KERYX 的内容与商品。', finalDescription: 'IP介绍、销售商品和样品订阅相互连接，可在各页面直接访问。', ip: '原创设计IP', shop: '商品商店', sample: '样品订阅',
  },
};

export default function AboutPage() {
  const { lang } = useLangContext(); const t = copy[lang];
  return <div className="min-h-screen bg-stone-50 text-stone-950"><RetailStoreHeader mode="company" showCart={false} /><main>
    <section className="border-b border-stone-200 bg-gradient-to-br from-stone-950 via-slate-900 to-indigo-950 text-white"><div className="mx-auto max-w-screen-xl px-4 py-16 sm:px-6 sm:py-24 lg:px-8"><p className="text-xs font-black tracking-[0.2em] text-orange-300">{t.eyebrow}</p><h1 className="mt-4 max-w-4xl text-4xl font-black leading-tight tracking-tight sm:text-6xl">{t.title}</h1><p className="mt-6 max-w-2xl text-base leading-7 text-stone-300 sm:text-lg">{t.lead}</p><div className="mt-10 flex flex-col gap-3 sm:flex-row"><Link href="/ip" className="inline-flex min-h-12 items-center justify-center gap-2 rounded-xl bg-white px-5 text-sm font-black text-stone-950 no-underline transition hover:bg-stone-100 active:scale-95">{t.ip}<ArrowRight className="h-4 w-4" /></Link><Link href="/shop" className="inline-flex min-h-12 items-center justify-center gap-2 rounded-xl border border-white/25 px-5 text-sm font-black text-white no-underline transition hover:bg-white/10 active:scale-95">{t.shop}<ArrowRight className="h-4 w-4" /></Link></div></div></section>
    <section className="mx-auto max-w-screen-xl px-4 py-12 sm:px-6 lg:px-8 lg:py-16"><div className="max-w-3xl"><p className="text-xs font-black tracking-[0.18em] text-orange-700">KERYX</p><h2 className="mt-2 text-3xl font-black tracking-tight">{t.introTitle}</h2><p className="mt-5 text-base leading-7 text-stone-600">{t.intro}</p></div><div className="mt-8 grid gap-4 md:grid-cols-3">{t.pillars.map((pillar) => { const Icon = pillar.icon; return <Link key={pillar.href} href={pillar.href} className="group rounded-3xl border border-stone-200 bg-white p-6 no-underline shadow-sm transition hover:-translate-y-1 hover:border-stone-300 hover:shadow-lg"><Icon className="h-7 w-7 text-orange-700" /><h3 className="mt-7 text-xl font-black text-stone-950">{pillar.title}</h3><p className="mt-3 min-h-20 text-sm leading-6 text-stone-600">{pillar.description}</p><span className="mt-6 inline-flex min-h-11 items-center gap-2 text-sm font-black text-stone-950 transition group-hover:text-orange-700">{pillar.cta}<ArrowRight className="h-4 w-4" /></span></Link>; })}</div></section>
    <section className="border-y border-stone-200 bg-white"><div className="mx-auto max-w-screen-xl px-4 py-12 sm:px-6 lg:px-8 lg:py-16"><p className="text-xs font-black tracking-[0.18em] text-orange-700">{t.flowEyebrow}</p><h2 className="mt-2 text-3xl font-black tracking-tight">{t.flowTitle}</h2><div className="mt-8 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{t.flow.map((item, index) => <article key={item.title} className="rounded-2xl border border-stone-200 bg-stone-50 p-5"><p className="text-sm font-black text-orange-700">0{index + 1}</p><h3 className="mt-8 text-lg font-black">{item.title}</h3><p className="mt-3 text-sm leading-6 text-stone-600">{item.description}</p></article>)}</div></div></section>
    <section className="mx-auto grid max-w-screen-xl gap-5 px-4 py-12 sm:px-6 lg:grid-cols-[1fr_1.2fr] lg:px-8 lg:py-16"><article className="rounded-3xl bg-orange-50 p-6 sm:p-8"><Boxes className="h-7 w-7 text-orange-700" /><h2 className="mt-7 text-2xl font-black">{t.trustTitle}</h2><ul className="mt-6 space-y-4">{t.trust.map((item) => <li key={item} className="flex gap-3 text-sm leading-6 text-stone-700"><span className="mt-2 h-2 w-2 shrink-0 rounded-full bg-orange-500" />{item}</li>)}</ul></article><article className="rounded-3xl bg-stone-950 p-6 text-white sm:p-8"><Compass className="h-7 w-7 text-orange-300" /><p className="mt-7 text-xs font-black tracking-[0.18em] text-orange-200">{t.originEyebrow}</p><h2 className="mt-2 text-2xl font-black">{t.originTitle}</h2><p className="mt-5 text-sm leading-7 text-stone-300">{t.origin}</p></article></section>
    <section className="mx-auto max-w-screen-xl px-4 pb-12 sm:px-6 lg:px-8 lg:pb-16"><div className="rounded-3xl border border-indigo-200 bg-indigo-50 p-6 sm:p-8"><BookOpenText className="h-7 w-7 text-indigo-700" /><h2 className="mt-6 text-2xl font-black">{t.finalTitle}</h2><p className="mt-3 max-w-2xl text-sm leading-6 text-stone-600">{t.finalDescription}</p><div className="mt-7 grid gap-3 sm:grid-cols-3">{[{ href: '/ip', label: t.ip }, { href: '/shop', label: t.shop }, { href: '/sample-subscription', label: t.sample }].map((item) => <Link key={item.href} href={item.href} className="inline-flex min-h-12 items-center justify-center gap-2 rounded-xl bg-white px-4 text-sm font-black text-stone-950 no-underline shadow-sm transition hover:bg-stone-100 active:scale-95">{item.label}<ArrowRight className="h-4 w-4" /></Link>)}</div></div></section>
  </main><PublicFooter /></div>;
}
